server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/userprofiledb
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user_service
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


#  redis:
#    host: localhost
#    port: 6378
#    timeout: 2000

